### ISSUE TITLE
The Java Method 'com.ibm.broker.IAM3.Log4jNode.initLog4j' could not be found.

### ISSUE THREAD

**Issue by dr-8898** [ot4i/node-for-log4j#12]
Hi. I already copied .par file in /jplugin and ensure that no Log4jLoggingNode_vX.X.jar, any jakarta-oro and log4j jar-files in shared-classes dir. But I'm still having his error upon deploying barfile. 

BIP3202E: (log4j.initLog4j, 1.1) : An error occurred when trying to resolve the Java class or method 'com.ibm.broker.IAM3.Log4jNode.initLog4j' which is referred to by the routine 'initLog4j'.
BIP2943E: The Java Method 'com.ibm.broker.IAM3.Log4jNode.initLog4j' could not be found as its containing class could not be found in the deployed bar file or in the 'workpath/shared-classes/' directory.

I also tried following steps from this [issue #5](https://github.com/ot4i/node-for-log4j/issues/5#issuecomment-1405377856) and still got the same deployment error.

**Comment by nieder-github** [comment]
If you deploy as suggested via the par file all the code of the node for log4j is only visible to the node for log4j.
This is due to the classloading of the broker and works as designed to isolate the code of this plugin from all other classes.
If you need to call the Java-Method of the node directly you must provide the jar-File as described here: [#4](https://github.com/ot4i/node-for-log4j/issues/4)

**Comment by nieder-github** [comment]
solved with version 2.1.0:
define a pluginFolder as policy ( ACE ) or Configurable Service ( IIB ) for your extensions
