### ISSUE TITLE
No socket error logs generated after log4j migration

### ISSUE THREAD

**Issue by t1091132** [ot4i/node-for-log4j#13]
Hello,
We are seeking your assistance regarding an issue we are experiencing with Log4j. While our Log4j configuration is successfully logging mandatory fields and other general logs, we are encountering difficulties in capturing specific error logs related to socket errors.
This issue occurs when we have all applications configured under one Log4j configuration. During IBM’s investigation, they recommended that we separate the Log4j configurations, assigning one application per Log4j configuration and when we remove the regex filter from the Log4j configuration. However, upon implementing this recommendation the first application log triggered became the only log file being used to all the application configured.
 
Example of what exactly the behavior:
log4j.xml composed app-1, app-2, app-3 and app-4.
1st trigger app-3 it logs in app-3.log 
2nd trigger app-2 it logs in app-3.log
3rd trigger app-4 it logs in app-3.log
 
Could you please provide us with the best practices or way on how to configure a log4j file that can accommodate multiple applications? Because right now we have 50 to 80 application in one log4j.xml that we are using regex as identifier on which logger file should the application log.
 
IBM has assured us that the ACE core functionality is operating as expected. Consequently, they have directed us to contact you for further assessment and investigation into this matter. We would like to raise this issue with you specifically in relation to the functionality of the IAM3 SupportPac.
as we are currently in the process of configuring our logging system using log4j version 2 for several applications within our organization. Given the number of applications we need to configure, we are seeking the most effective way to manage this setup.

For your reference:

WORKING-socket error being logged
Log4j ver 1
jakarta-oro-2.0.4
log4j-1.2.8
Log4jLoggingNode_v1.2.4

NOT WORKING-socket error not being logged
Log4j ver 2
jakarta-oro-2.0.8
log4j-api-2.17.1
log4j-core-2.17.1
Log4jLoggingNode_v2.0.0
 
Your expertise in this matter would be greatly appreciated, as we aim to resolve this issue promptly.
Thank you for your attention and support.

**Comment by nieder-github** [comment]
1) It is not possible to run IAM3 with multiple log4j configuration files. The first configuration file found in the first instance that runs will be the one that configures log4j.
2) In order to separate your logs I suggest to use the "Logger Name" parameter. This way you can separate your logs easily.
Simply define a Logger section in your log4j configuration file for each "Logger name" you use in your flows then.
You can then define AppenderRefs for each Logger, e.g.:
<Loggers>
<Logger name="App1" level="WARN">
   <AppenderRef ref="AppenderForFile1">
</Logger>
<Logger name="App2" level="WARN">
   <AppenderRef ref="AppenderForFile2">
</Logger>
<Root level="WARN">
   <AppenderRef ref="AppenderXY">
</Root>
</Loggers>
3) In order to help you with your socket error problem I need more information about your configuration and appenders /  filters used. 
But: I it seems to be a log4j configuration issue, that I might help, but seems not primarily be an IAM3 issue.

**Comment by t1091132** [comment]
Hello nieder-github,
 
We have uploaded our Log4j version 2.17.1 configuration sample for your reference. In this sample, we have included configurations for five applications. 
 
We would greatly appreciate your assistance in identifying and resolving the problem.
 
Thank you.

[Log4jv2.17.zip](https://github.com/user-attachments/files/16490242/Log4jv2.17.zip)

**Comment by nieder-github** [comment]
To me you reported 2 problems:
1) log files are not separated
2) socket error not reported

To 1) I've already responded
So I assume we are now talking about 2).
For this I need even more information. If the socket error is not logged, it may be that the filter you are using does not fit.
In order to help I need more details.

PS: Have you tried my solution for 1). Maybe this also solves the problem with the socket error, because you don't need a filter then.

**Comment by t1091132** [comment]
Hello,
 
Regarding the solution for number 1, where you mentioned that it is not possible to run IAM3 with multiple Log4j configuration files, we want to clarify that we are actually using a single Log4j configuration file that includes configurations for multiple applications. We have already attempted this approach without success. Please see the zip file below of log4j config for your reference. Additionally, within our configuration file, we are using a regex filter to match our logs for each application. Thank you.
[log4jv2.zip](https://github.com/user-attachments/files/16504432/log4jv2.zip)

**Comment by nieder-github** [comment]
I want to make clear that we are talking about log4j configuration. As the node for log4j seems to work ( the config file is used and (some) output is written ).
Nevertheless:
I do not see any logger configuration beside Root logger in the zip you provided !! See my suggestion in my first answer.
To further analyze I really need more information about your error messages ( the node configuration + message ) that you want to log.
1) So you state, that the filter config does not work ?
-> Then this seems to be a filter configuration problem. I need the message you want to log.
2) a socket error is not logged at all ?
-> I need to see the error message you want to log.
BTW: You can test log4j configurations with simple Java test files....

**Comment by t1091132** [comment]
Hello,
 
We already tried what you suggested last time adding a logger to the logger's part. Unfortunately, it didn't work for us. It didn't log anything. For reference of the configuration that we have done please see the configuration file included in the zip file.
I've attached the error log that we want to capture in our system for your reference. Please see zip file below.

zip file name: ErrorLog and Config
Files:
   SocketErrorLog
   Log4jv2.17.1_SampleConfig


Thank you.

[ErrorLog and Config.zip](https://github.com/user-attachments/files/16518591/ErrorLog.and.Config.zip)

**Comment by nieder-github** [comment]
I could reproduce your problem.
The problem is the multiline error message. The "." does not to include line break characters.
Please try or experiment with something like:
<RegexFilter regex=&quot;.\*APP_App1[A-Za-z0-9 \t\r\n\v\f\\\]\\\[\\\!\\\&quot;\\\#\\\$\\\%\\\&amp;\\\&pos;\\\(\\\)\\\*\\\+\\\,\\\.\\\/\\\:\\\;\\\&lt;\\\=\\\&gt;\\\?\\\@\\\^\\\_\\\`\\\{\\\|\\\}\\\~\\\-]*&quot; onMatch="ACCEPT" onMismatch="DENY" useRawMsg="true"/>

But as I mentioned:
If you use my suggestion utilizing the logger name, you do not need filters any more.

**Comment by t1091132** [comment]
Hello,
 
I wanted to let you know that we are currently implementing the solution you suggested with the logger name. We have ongoing testing in progress, and we'll keep you updated if we require any further assistance.
 
For now, that covers everything on our end.
 
Thank you for your help.

**Comment by nieder-github** [comment]
Problem solved: Log4j RegexFilter usage replaced by utilizing dedicated loggers.
